### PR TITLE
Add Korean translate

### PR DESCRIPTION
**Pull request by green1052**
Co-authored-by: jackfrost <jackfrost5446@naver.com>

#697

### CODE REVIEW

**Comment by green1052** [comment]
@Sid127

**Comment by Sid127** [comment]
thank you for the swift response, and sorry it took so long for us again

@felixlinker we're good to go on this one

**Comment by green1052** [comment]
that's ok

**Comment by felixlinker** [comment]
For the next time, you can simply edit your pull request to target a different branch, no need to open another one :) (Not that I'd care, but should be simpler for you.)

Thanks for the work @Sid127 and @green1052

**Pull request merged**
