### PR TITLE
Fix stroke-width handling bug in Safari 11

### PR DESCRIPTION
**Pull request by kamenlitchev**
Attempt fixing issue #118 by extracting SVG stroke-width attribute in separate CSS definition. Note that it's my first Less code, so feel free to not like :)

### CODE REVIEW

**Comment by strideynet** [comment]
Modifying PR to effect the develop branch!

**Comment by strideynet** [comment]
I will test this PR tonight on my local machine as Travis is still skew whiff.

**Comment by kamenlitchev** [comment]
Thanks! Did not know which branch to issue the request to - wondered if it is to-Dev, then some Release branch, then Master.

**Comment by strideynet** [comment]
Have you tested the fix locally?

**Comment by kamenlitchev** [comment]
Just tested it. Never did Node.js before, so took some time. Aaand turned out I had to fix few more rules (though I clearly remember fixing the slot.empty rule, strange).

Sorry for this second commit!!!

Attached is a screenshot of how the latest kamenlitchev/master looks on Safari 11

screen shot 2017-08-29 at 15 04 20

**Comment by strideynet** [comment]
Merged into Develop branch for next feature release. Many thanks.

**Pull request merged**
