### PR TITLE
Add Korean translate

### PR DESCRIPTION
**Pull request by green1052**
thank you jackfrost, rollbap

### CODE REVIEW

**Comment by Sid127** [comment]
Hi! Sorry for getting around to this so late, the changes look good to me! Though, could you rewrite your PR such that the merge commit [c9fb7cb](https://github.com/EDCD/coriolis/pull/697/commits/c9fb7cb8f36a5b92ebef86885d3de33db542e907) isn't there? It's needlessly confusing to have merge commits that point nowhere

**Comment by green1052** [comment]
ok i will be create new pr

**Comment by green1052** [comment]
@Sid127 push devlop br? or master?

**Comment by Sid127** [comment]
PR to develop branch, please and thank you

**Pull request closed without merging**
