### PR TITLE
shield recovery time depending on distributor draw

### PR DESCRIPTION
**Pull request by ItsUnknownGamer**
When engineering shields the distributor draw can vary from 0.6 which was hard-coded in the calculation function. I corrected this and verified new values. Simple check: Change distributor draw manually without change - nothing happens, with change it is calculated correctly.

### CODE REVIEW

**Comment by Sid127** [comment]
@felixlinker this seems okay to me, tested by hosting locally and generating values, then using a ship in-game to test time taken for recovery (building from 0 to 50%). I also cross checked the numbers with what it says on EDSY, fwiw

**Comment by felixlinker** [comment]
Thanks for the extensive testing @Sid127

**Comment by felixlinker** [comment]
Sorry had to revert PR because the PR targeted master and I didn't notice that upon first glance. I'll manually merge into develop and push.

**Comment by felixlinker** [comment]
Merge into develop here: https://github.com/EDCD/coriolis/commit/887dbc25f8b0cba0356ce07b6616ee9c0baeb72f

**Pull request merged**
