### PR TITLE
Migrated from less to sass, removed unused rollup and local d3 copy

### PR DESCRIPTION
**Pull request by jeneg**
This will be part one of migrating to latest dev env and libs
@felixlinker please take a look.

### CODE REVIEW

**Comment by felixlinker** [comment]
Why sass over less?

**Comment by jeneg** [comment]
Main reason is that sass is supported out of the box by react-scrips and it will be simpler to migrate. Also it looks more popular and maintainable currently with minimum changes from project side (mostly renaming variables from @ to $ and some mixin changes)

**Comment by felixlinker** [comment]
But there are still sass dependencies, right? What does it mean to work out of the box? Can you reference the classes in jsx code more easily?

**Comment by jeneg** [comment]
Yes, they will be just swapped from less to sass, nothing will be changed from developer stand of point at this stage. This will help to easier integrate to `react-scripts` please check https://create-react-app.dev/docs/adding-a-sass-stylesheet for more info.
Regarding referencing classes in code it works fine for me both in sass and less when using `className` but both fail with using `classnames` lib (using WebStorm)

**Comment by felixlinker** [comment]
Okay, I also don't really know the benefit of `react-scripts` 😄

When you say both fail with `classnames`, aren't we using that lib?
https://github.com/EDCD/coriolis/blob/2bb55d2c3613a3422e6c63f6131c9cbef29821cb/package.json#L127

**Comment by jeneg** [comment]
> When you say both fail with `classnames`, aren't we using that lib?

We do, and looks like if you adding css class just inside `className` IDE can resolve and type ahead corresponding class names, but when you adding classes using `classnames` it can't resolve those. But I believe this is IDE related stuff and not about used preprocessor.

> Okay, I also don't really know the benefit of `react-scripts` 😄

I'll copy our PM message here to keep track:)

I see number of benefits :
- it has well defined structure and great documentation
- contains all required scripts for running, building testing etc.
- it is preconfigured so all babel and compilation scripts can be removed from project deps
- allows easy switch to TS in future
- easy deps update

So main benefit that I see that you don't have to take care about infrastructure but focus on app itself :)

**Pull request closed without merging**
