### PR TITLE
Corrected calculations of modification values

### PR DESCRIPTION
**Pull request by jeneg**
Fixed calculations for modification values according to #624. Previous version of calculations was weird for me, but point me if I'm missing something.

@felixlinker please check

Screenshot_17
Screenshot_18

### CODE REVIEW

**Comment by felixlinker** [comment]
@jeneg Thanks for the effort to continuously look at issues!

I worried whether this change is correct overall, though. There are four types of modifications:
- Additive
- Multiplicative
- Overwrite
- Boost

Whereas the first three should be straight-forward, the latter is harder to understand. I think shield booster addition is modified by boosting. What you do here is multiply the base-value plus one with the blueprint modifier, then subtract one again, e.g.: `(1 + value) * bp_modifier - 1`. This way, you get better results than simply by multiplying, because your base is bigger.

My feeling tells me that the last line you modified was intended to cope with this.

**Comment by jeneg** [comment]
Hey, @felixlinker thanks for your response. 
In provided case I've checked `thermload` that has base value of `-6000` (-60%) and multiplicative modifier 
```
  "special_engine_cooled": {
    "mass": 0.05,
    "thermload": -0.1
  },
```
that should decrease value by 10% so method should return `-7000` (-70%) but it returns ~`-6399` (-64%).
Maybe multiplicative should also be handled in separated if condition? Which modifications should be handled by code that you mentioned?

**Comment by jeneg** [comment]
Investigated a bit more and looks like calculations messed up also for `'explres', 'kinres', 'thermres', 'causres'` section. those additions/subtractions of `1` is producing wrong result

**Before**

```js
if (includes(['explres', 'kinres', 'thermres', 'causres'], name)) {
  // Apply resistance modding mechanisms to special effects subsequently
  result = result + modifierActions[name] * (1 - (this[name] + result / multiplier)) * 100;
}
```

Screenshot_21
Screenshot_22

**After**

```js
if (includes(['explres', 'kinres', 'thermres', 'causres'], name)) {
  // Apply resistance modding mechanisms to special effects subsequently
  result = result + modifierActions[name] / 100 * multiplier;
}
```

Screenshot_23
Screenshot_24

**Comment by felixlinker** [comment]
The problem with resistances is that they are handled as damage multipliers in the game (for 20% resistance the damage multiplier us 0.8; for -30% it is 1.3). Blueprints change resistance not by resistance but multiplicatively by the damage multiplier. This is not handled perfectly in the pipeline. Coriolis shows you the damage multiplier reactor of the blueprint in the tooltip. I would suggest against changing this, because I have other changes in the pipeline that would address this.

Coming to your other comments: properties that are modified by the boost method, i.e. the +1 multiplicative method, are shield boost and hull boost.

I think the issue with the odd values for heat rate modifiers on thrusters is that thrusters don't have the thermal load property to begin with in coriolis-data. It's always 0. I can see, why this might cause issues. And even if this is not the issue, this should be addressed before we face the modifiers.

It's great that you deep dive these topics! Your help is very much appreciated :)

**Comment by felixlinker** [comment]
I just double checked your results. Let me summarize my picture of the matter: the +/-1 things is messing up the numbers - right? And you didn't find a case in which it actually worsened things - right?

That being said, it just occurred to me that when I did research for ed-forge, all boost modifiers are shown as additive. This would also align with your PR.

**Comment by jeneg** [comment]
Hey @felixlinker, sorry for delayed response. Yes, as I see proposed changes will give same result for modifications as Inara does. But it also affect summary calculations and ideally this should be retested by someone who knows entire kitchen. I may missing something at this point.

**Comment by felixlinker** [comment]
We now have a develop server again, so I will just merge your PR and test it out no the beta site :)

**Comment by felixlinker** [comment]
I try to get all my servers running properly and then we should be able to see the changes on https://beta.coriolis.io

**Comment by jeneg** [comment]
Thanks! I will probably raise another PR as this one not containing changes for my latest findings regarding 

> Investigated a bit more and looks like calculations messed up also for 'explres', 'kinres', 'thermres', 'causres' section. those additions/subtractions of 1 are producing wrong result

**Comment by felixlinker** [comment]
@jeneg The problem with the resistances is a different one and hard to solve at this stage of coriolis. Resistances are modified as damage multipliers (30% resistance = 0.7 damage multiplier), i.e. the blueprint contains a factor that applies to the damage multiplier.

You can only know the true modifier of the resistance if you also know the base damage multiplier of the module you apply the blueprint to. We could change the pipeline, but I would judge the modifiers for resistances as "good enough". To my knowledge, they're also displayed skewed in-game and on inara because of the exact same reason.

**Comment by felixlinker** [comment]
If you want, you can also hop onto the EDCD Discord, and I tell you what's happening behind the curtains right now :) This way, you might get a better feeling of what you'd like to pick up :)

**Comment by jeneg** [comment]
> if you also know the base damage multiplier of the module you apply the blueprint to
is this something known? if so we can probably make correct calculations then

**Comment by felixlinker** [comment]
> is this something known? if so we can probably make correct calculations then

What do you mean by "known"? At least I know it 😛

To implement this, you have three bad options.

1. Duplicate the code to calculate applying resistance modifiers.
2. Instantiate a new module of the same type and apply the blueprint, then throw the module away.
3. Apply the blueprint to the current module, then roll-back the state.

I don't like either of these, they all seem brittle and hard to understand for future maintainers with a minimal upside to show the "overall correct modifier" whereas other places (both in inara and in-game) show somewhat "wrong" modifiers as well.

**Comment by felixlinker** [comment]
One thing I just noticed; edsy shows additional reduction of thermal load by thermal spread as -4%? (cf. https://edsy.org/#/L=FS00000H4C0S00,,,9p300A7g00AMgG03L_W0Acw00ApQ00B4c00BKE00Bb600,,)

**Pull request merged**
