### PR TITLE
Feature/#293 header keynav

### PR DESCRIPTION
**Pull request by pnellesen**
Added keydown and focus handlers for Slot Section Menus ("Core Internal", "Optional Internal", etc.)

When focus is on the header, Enter key will open the menu and set focus to either the first option, or else the currently selected option, such as "Planetary Explorer" in Core Internal menu (if one has been previously selected).

While menu is open, Tab and Shift-Tab will move the focus up and down as expected. Shift-tab on first option will move focus to last option in the menu, and Tab on the last option will move focus to the top. Focus will stay inside the menu until menu is closed.

When focus is on a menu options, hitting the Enter key will trigger the onClick function for that option, and will set the option as the currently selected option for that menu.

Esc key will close the menu and set focus to the menu header H1 element.

### CODE REVIEW

**Comment by pnellesen** [comment]
Will fix JSDoc issues and re-commit

**Comment by willyb321** [comment]
I just fixed around 500 lint issues, if you could merge in those changes and resolve the conflict that would be dank!

Thanks

**Comment by pnellesen** [comment]
Changes merged and conflicts resolved on my local

**Comment by willyb321** [comment]
Awesome, is this ready for merge?

**Pull request merged**
