### PR TITLE
 Update the SLEF import to support engineering modifications from inara

### LINKED ISSUE #631: Import missing engineering information
When exporting data from Inara to Coriolis no engineering is shown on coriolis. Speaking to Artie from Inara, he says the problem is on coriolis side.

Here an example of an ship export:
`[{"header":{"appName":"Inara","appVersion":"1.0","appURL":"https:\/\/inara.cz\/cmdr-fleet\/292951\/2510292\/","appCustomProperties":{"inaraCommanderID":292951,"inaraShipID":2510292}},"data":{"Ship":"krait_light","ShipID":4,"ShipName":"New Frontier","ShipIdent":"LWT303","HullValue":30438198,"ModulesValue":22590193,"Rebuy":2651421,"Modules":[{"Slot":"tinyhardpoint1","Item":"hpt_plasmapointdefence_turret_tiny","On":false,"Priority":2},{"Slot":"tinyhardpoint2","Item":"hpt_plasmapointdefence_turret_tiny","On":false,"Priority":2},{"Slot":"tinyhardpoint3","Item":"hpt_heatsinklauncher_turret_tiny","On":true,"Priority":1},{"Slot":"tinyhardpoint4","Item":"hpt_cloudscanner_size0_class2","On":true,"Priority":2},{"Slot":"slot01_size6","Item":"int_cargorack_size6_class1","On":true,"Priority":1},{"Slot":"slot02_size5","Item":"int_fuelscoop_size5_class5","On":true,"Priority":2},{"Slot":"slot03_size5","Item":"int_cargorack_size5_class1","On":true,"Priority":1},{"Slot":"slot04_size5","Item":"int_guardianfsdbooster_size5","On":true,"Priority":2},{"Slot":"slot05_size3","Item":"int_shieldgenerator_size3_class3_fast","On":true,"Engineering":{"BlueprintName":"shieldgenerator_optimised","Level":3,"Quality":1,"ExperimentalEffect":"special_shield_health"}},{"Slot":"slot06_size3","Item":"int_cargorack_size3_class1","On":true,"Priority":1},{"Slot":"slot07_size3","Item":"int_dronecontrol_collection_size3_class4","On":true,"Priority":2},{"Slot":"slot08_size2","Item":"int_buggybay_size2_class2","On":true,"Priority":3},{"Slot":"slot09_size1","Item":"int_detailedsurfacescanner_tiny","On":true,"Engineering":{"BlueprintName":"sensor_expanded","Level":5,"Quality":1}},{"Slot":"powerplant","Item":"int_powerplant_size3_class5","On":true,"Priority":1,"Engineering":{"BlueprintName":"powerplant_armoured","Level":5,"Quality":1,"ExperimentalEffect":"special_powerplant_highcharge"}},{"Slot":"mainengines","Item":"int_engine_size4_class5","On":true,"Engineering":{"BlueprintName":"engine_tuned","Level":2,"Quality":1,"ExperimentalEffect":"special_engine_overloaded"}},{"Slot":"frameshiftdrive","Item":"int_hyperdrive_size5_class5","On":true,"Engineering":{"BlueprintName":"fsd_longrange","Level":4,"Quality":0.817}},{"Slot":"lifesupport","Item":"int_lifesupport_size4_class2","On":true,"Priority":1},{"Slot":"powerdistributor","Item":"int_powerdistributor_size4_class5","On":true,"Engineering":{"BlueprintName":"powerdistributor_highfrequency","Level":3,"Quality":1,"ExperimentalEffect":"special_powerdistributor_capacity"}},{"Slot":"radar","Item":"int_sensors_size6_class2","On":true,"Engineering":{"BlueprintName":"sensor_lightweight","Level":3,"Quality":1}},{"Slot":"fueltank","Item":"int_fueltank_size5_class3","On":true,"Priority":1},{"Slot":"armour","Item":"krait_light_armour_grade1","On":true,"Priority":1,"Engineering":{"BlueprintName":"armour_heavyduty","Level":1,"Quality":1}}]}}]`

### PR DESCRIPTION
**Pull request by mmathias01**
This is an attempt to resolve #631

In my local testing this *seems* to be getting the same results and calculations as I get when I build a ship manually with the same modifications. It also is fairly close to what I am seeing in other ship loadout / build tools. With that being said I would welcome some additional testing on this by someone who knows more of the underlying mechanisms to make sure I didn't miss anything.

P.S. I put in A LOT of logging so that I could see what was going on, I left it in place because it is helpful for development and I figured that webpack was probably stripping that out for productions builds anyway.

### CODE REVIEW

**Comment by felixlinker** [comment]
It seems to me that this PR doesn't allow to import modifiers anymore, right? You only look at the quality, even if modifiers are present. This would improve the situation for any inara import but would worsen it for all others, e.g. EDMC imports.

**Comment by felixlinker** [comment]
Hey @mmathias01,

It has been a while :) Do you have comments on my understanding of your PR? Would be good if we could settle this! After all, this improves a crucial bug with coriolis.

Best

**Comment by alexeygorb** [comment]
Hi, @felixlinker this PR seems to be stuck, right? I think I will be able to fix the issue you described with "Modifiers" so that if the Modifiers is not provided, it will derive the logic based on the quality parameter.
Do I just create a new PR for it?

**Comment by felixlinker** [comment]
Closed in favour of #673

**Pull request closed without merging**
