### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by gopstr**
This PR fixes some existing Russian translations and adds many new strings.

Also I found misprint in 'power distriubtor', so I had to change `de.json`.

It seems my IDE changed CRLF to LF in all modified files so it shows much more changes than expected. I'm not sure how to return line breaks back.

### CODE REVIEW

**Comment by gopstr** [comment]
@felixlinker Can you please review this PR?

**Comment by felixlinker** [comment]
Don't worry about the line endings. Someone set them to CR LF once (which is bad - non standard). It'll happen eventually.

**Comment by felixlinker** [comment]
Did you test the changes locally?

**Comment by gopstr** [comment]
> Did you test the changes locally?

yes, I did

**Pull request merged**
